#!/usr/bin/env python3
"""Build the standalone deployment artifact from the modular source files."""

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent
MODULES = ("contexts.py", "composer.py", "conversation_handlers.py", "bot.py")

# Names of the local modules being concatenated. Any `from <name> import ...`
# line referencing one of these is an inter-module import that becomes
# unnecessary (and unresolvable, since there's no separate module file
# anymore) once everything is pasted into one file, so it must be stripped.
#
# This is regex-based against the module *names*, not hardcoded against the
# exact import statement text, on purpose: a previous version hardcoded the
# literal statements (e.g. "from contexts import merchant_display_name,
# parse_iso_date\n") and silently stopped matching the moment bot.py's actual
# import line changed (e.g. gained new imported names), which shipped a
# vera_bot_single_file.py that raised ModuleNotFoundError on standalone
# import. A regex keyed on the module name can't drift out of sync the same
# way -- it strips the import line whatever names it pulls in.
LOCAL_MODULE_NAMES = ("contexts", "composer", "conversation_handlers")
_LOCAL_IMPORT_RE = re.compile(
    r"^from (?:" + "|".join(LOCAL_MODULE_NAMES) + r") import (?:\([^)]*\)|[^\n]*)\n",
    re.MULTILINE,
)


def strip_local_imports(source: str) -> str:
    source = source.replace("from __future__ import annotations\n", "")
    return _LOCAL_IMPORT_RE.sub("", source)


def main() -> None:
    sections = [
        "#!/usr/bin/env python3\n",
        '"""Generated by build_single_file.py; do not edit directly."""\n',
        "from __future__ import annotations\n\n",
    ]
    for filename in MODULES:
        source = strip_local_imports((ROOT / filename).read_text(encoding="utf-8"))
        sections.extend((f"\n# --- Begin {filename} ---\n", source, f"\n# --- End {filename} ---\n"))
    (ROOT / "vera_bot_single_file.py").write_text("".join(sections), encoding="utf-8")


if __name__ == "__main__":
    main()
