#!/usr/bin/env python3
"""Build the standalone deployment artifact from the modular source files."""

from pathlib import Path


ROOT = Path(__file__).resolve().parent
MODULES = ("contexts.py", "composer.py", "conversation_handlers.py", "bot.py")
LOCAL_IMPORTS = (
    "from contexts import (\n",
    "from composer import compose\n",
    "from conversation_handlers import respond as conv_respond, new_state\n",
    "from contexts import merchant_display_name, parse_iso_date\n",
)


def strip_local_imports(source: str) -> str:
    source = source.replace("from __future__ import annotations\n", "")
    for statement in LOCAL_IMPORTS:
        if statement == "from contexts import (\n":
            start = source.find(statement)
            if start >= 0:
                end = source.find(")\n", start) + 2
                source = source[:start] + source[end:]
        else:
            source = source.replace(statement, "")
    return source


def main() -> None:
    sections = [
        "#!/usr/bin/env python3\n",
        '"""Generated by build_single_file.py; do not edit directly."""\n',
        "from __future__ import annotations\n\n",
    ]
    for filename in MODULES:
        source = strip_local_imports((ROOT / filename).read_text(encoding="utf-8"))
        sections.extend((f"\n# --- Begin {filename} ---\n", source, f"\n# --- End {filename} ---\n"))
    (ROOT / "vera_bot_single_file.py").write_text("".join(sections), encoding="utf-8")


if __name__ == "__main__":
    main()
