#!/usr/bin/env python3
"""Generated by build_single_file.py; do not edit directly."""
from __future__ import annotations


# --- Begin contexts.py ---
"""
contexts.py — safe accessors over the raw dicts loaded from the dataset JSON.

We deliberately do NOT build strict dataclasses that raise on missing fields.
Real pushes (per challenge-testing-brief.md §4 Phase 3) can be partial,
generated (non-seed) merchants/triggers are sparser than the seeds, and a
composer that crashes on a missing key is worse than one that degrades
gracefully. Every getter here returns a safe default instead of KeyError.
"""

from datetime import datetime, timezone
from typing import Any, Iterable, Optional


# ---------------------------------------------------------------------------
# generic safe getters
# ---------------------------------------------------------------------------

def g(d: Optional[dict], *path, default=None):
    """Nested safe-get: g(merchant, 'identity', 'name', default='there')."""
    cur = d
    for p in path:
        if not isinstance(cur, dict):
            return default
        cur = cur.get(p)
    return cur if cur is not None else default


def is_placeholder_payload(trigger: dict) -> bool:
    """Generated (non-seed) triggers carry payload={'placeholder': True, ...}
    with no real facts. Composer must not cite numbers from these."""
    return bool(g(trigger, "payload", "placeholder", default=False))


# ---------------------------------------------------------------------------
# category helpers
# ---------------------------------------------------------------------------

def digest_by_id(category: dict, item_id: Optional[str]) -> Optional[dict]:
    if not item_id:
        return None
    for item in g(category, "digest", default=[]) or []:
        if item.get("id") == item_id:
            return item
    return None


def digest_by_kind(category: dict, kind: str) -> list[dict]:
    return [d for d in (g(category, "digest", default=[]) or []) if d.get("kind") == kind]


def freshest_digest_for_trigger(category: dict, trigger: dict, *kinds: str) -> Optional[dict]:
    """Resolve a trigger to its supplied digest item, then to a fresh relevant item.

    Phase 3 of the official harness replaces category contexts with newly
    injected digest entries.  Falling back to the last matching entry lets a
    known trigger family benefit from that newer context without assuming a
    seed-only identifier or inventing a citation.
    """
    payload = g(trigger, "payload", default={}) or {}
    for key in ("top_item_id", "digest_item_id", "item_id", "source_item_id"):
        item = digest_by_id(category, payload.get(key))
        if item:
            return item
    wanted = {kind.lower() for kind in kinds if kind}
    matches = [
        item for item in (g(category, "digest", default=[]) or [])
        if str(item.get("kind", "")).lower() in wanted
    ]
    return matches[-1] if matches else None


def seasonal_beat_for_month(category: dict, month_abbr: str) -> Optional[dict]:
    """month_abbr like 'Apr'. Matches against 'month_range' strings like 'Apr-Jun'."""
    for beat in g(category, "seasonal_beats", default=[]) or []:
        rng = beat.get("month_range", "")
        if month_abbr in rng:
            return beat
    return None


def taboo_words(category: dict) -> list[str]:
    return [w.lower() for w in g(category, "voice", "vocab_taboo", default=[]) or []]


def violates_taboo(text: str, category: dict) -> list[str]:
    low = text.lower()
    return [w for w in taboo_words(category) if w in low]


def uses_code_mix(category: dict) -> bool:
    return "hindi" in (g(category, "voice", "code_mix", default="") or "").lower()


# ---------------------------------------------------------------------------
# merchant helpers
# ---------------------------------------------------------------------------

def merchant_display_name(merchant: dict) -> str:
    return g(merchant, "identity", "name", default="there")


def owner_salutation(merchant: dict, category: dict) -> str:
    """Pick a salutation consistent with category voice + actual owner name."""
    first = g(merchant, "identity", "owner_first_name")
    examples = g(category, "voice", "salutation_examples", default=[]) or []
    if first:
        # dentists use "Dr. {first_name}" style if present in examples
        for ex in examples:
            if "{first_name}" in ex:
                return ex.replace("{first_name}", first)
        return first
    return merchant_display_name(merchant)


def merchant_speaks_hindi(merchant: dict) -> bool:
    return "hi" in (g(merchant, "identity", "languages", default=[]) or [])


def active_offers(merchant: dict) -> list[dict]:
    return [o for o in (g(merchant, "offers", default=[]) or []) if o.get("status") == "active"]


def has_signal(merchant: dict, prefix: str) -> Optional[str]:
    """merchant.signals is a list of free-form strings like 'stale_posts:22d'.
    Returns the first signal string starting with `prefix`, else None."""
    for s in g(merchant, "signals", default=[]) or []:
        if s.startswith(prefix):
            return s
    return None


def signal_number(signal_str: Optional[str]) -> Optional[str]:
    """'stale_posts:22d' -> '22d'. 'dormant_with_vera_38d' -> None (no colon) —
    caller should use regex for underscore-joined variants if needed."""
    if not signal_str or ":" not in signal_str:
        return None
    return signal_str.split(":", 1)[1]


def review_theme(merchant: dict, theme_substr: Optional[str] = None) -> Optional[dict]:
    themes = g(merchant, "review_themes", default=[]) or []
    if not themes:
        return None
    if theme_substr:
        for t in themes:
            if theme_substr in t.get("theme", ""):
                return t
    return themes[0]


def last_conversation_turn(merchant: dict) -> Optional[dict]:
    hist = g(merchant, "conversation_history", default=[]) or []
    return hist[-1] if hist else None


def merchant_engaged_recently(merchant: dict) -> bool:
    last = last_conversation_turn(merchant)
    if not last:
        return False
    return last.get("from") == "merchant" or "intent" in (last.get("engagement") or "")


# ---------------------------------------------------------------------------
# customer helpers
# ---------------------------------------------------------------------------

def customer_first_name(customer: dict) -> str:
    name = g(customer, "identity", "name", default="")
    # strip "(parent: X)" / "(walk-in, no profile)" annotations for the greeting
    if "(" in name:
        name = name.split("(")[0].strip()
    return name or "there"


def customer_wants_code_mix(customer: dict) -> bool:
    pref = (g(customer, "identity", "language_pref", default="") or "").lower()
    return "mix" in pref or pref in ("hi", "hindi")


def customer_pure_hindi(customer: dict) -> bool:
    pref = (g(customer, "identity", "language_pref", default="") or "").lower()
    return pref == "hi"


def customer_has_consent(customer: Optional[dict], required_scope: Optional[str | Iterable[str]]) -> bool:
    """Return whether a customer has consent for a trigger's outreach purpose.

    Customer triggers are not sufficient proof of consent: the judge can inject
    new customer contexts specifically to verify that outreach respects the
    consent scope supplied with that customer.
    """
    if not customer or not required_scope:
        return False
    scopes = g(customer, "consent", "scope", default=[]) or []
    required = {required_scope} if isinstance(required_scope, str) else set(required_scope)
    return bool(required & set(scopes))


# ---------------------------------------------------------------------------
# formatting helpers
# ---------------------------------------------------------------------------

def fmt_pct(x: Optional[float]) -> str:
    if x is None:
        return "?"
    return f"{'+' if x >= 0 else ''}{round(x * 100)}%"


def fmt_money(x) -> str:
    try:
        return f"₹{int(x):,}"
    except (TypeError, ValueError):
        return str(x)


def parse_iso_date(s: Optional[str]) -> Optional[datetime]:
    """Parses both bare dates ('2026-05-12') and full ISO timestamps
    ('2026-05-12T18:00:00+05:30' / '...Z'). Always returns a tz-aware
    datetime (naive dates are assumed UTC) so subtraction never raises."""
    if not s:
        return None
    try:
        s2 = s.replace("Z", "+00:00")
        d = datetime.fromisoformat(s2)
        if d.tzinfo is None:
            d = d.replace(tzinfo=timezone.utc)
        return d
    except ValueError:
        return None


def days_between(iso_a: Optional[str], iso_b: Optional[str]) -> Optional[int]:
    a, b = parse_iso_date(iso_a), parse_iso_date(iso_b)
    if not a or not b:
        return None
    return abs((b - a).days)


def month_abbr(iso_s: Optional[str]) -> Optional[str]:
    d = parse_iso_date(iso_s)
    return d.strftime("%b") if d else None

# --- End contexts.py ---

# --- Begin composer.py ---
"""
composer.py — EngagementComposer: compose(category, merchant, trigger, customer?) -> dict

Design choice (see README): fully deterministic, template-driven composition
grounded directly in the structured contexts, dispatched by trigger `kind`
into "framing families" (per engagement-design.md §Composer: "different kind
values may use different prompt variants ... the composer dispatches by
kind"). No LLM call in the hot path:
  - guarantees determinism (challenge-brief.md §7.1 requirement)
  - guarantees <30s / no network dependency (challenge-testing-brief.md §5)
  - structurally impossible to fabricate a number: every citable fact is
    pulled from the dict, never invented — the anti-fabrication constraint
    (challenge-brief.md §5.8) is enforced by construction, not by hoping an
    LLM won't hallucinate under time pressure.

Every family function returns a dict:
    { body, cta, send_as, suppression_key, rationale, template_params }
"""

from typing import Any, Optional


MAX_BODY_CHARS = 700  # generous soft cap; WhatsApp itself allows far more


# ---------------------------------------------------------------------------
# public entry point
# ---------------------------------------------------------------------------

def compose(category: dict, merchant: dict, trigger: dict,
            customer: Optional[dict] = None) -> dict:
    kind = trigger.get("kind", "")
    fn = FAMILY_DISPATCH.get(kind, _generic_fallback)
    try:
        result = fn(category, merchant, trigger, customer)
    except Exception as e:  # composer must never 500 the /tick endpoint
        result = _generic_fallback(category, merchant, trigger, customer)
        result["rationale"] += f" [fallback after error in '{kind}' handler: {e}]"

    result["body"] = result["body"].strip()
    if len(result["body"]) > MAX_BODY_CHARS:
        result["body"] = result["body"][: MAX_BODY_CHARS - 1].rstrip() + "…"

    # single-CTA guard: if more than one '?' slipped through a family
    # template, collapse every question but the last into a statement —
    # the brief is explicit that a send must carry exactly one ask
    # (challenge-brief.md §5: "one clear CTA per send").
    q_count = result["body"].count("?")
    if q_count > 1:
        import re as _re
        parts = _re.split(r"(?<=\?)\s+", result["body"])
        fixed = [p.rstrip("?").rstrip() + "." if i < len(parts) - 1 and p.endswith("?") else p
                 for i, p in enumerate(parts)]
        result["body"] = " ".join(fixed)
        result["rationale"] += " [single-CTA guard: collapsed extra '?' into statements]"

    # last-mile taboo guard: category voice taboos must never appear
    bad = violates_taboo(result["body"], category)
    if bad:
        for w in bad:
            result["body"] = _strip_word_ci(result["body"], w)
        result["rationale"] += f" [stripped taboo term(s): {', '.join(bad)}]"

    result.setdefault("suppression_key", trigger.get("suppression_key", ""))
    result.setdefault("send_as", "merchant_on_behalf" if customer else "vera")
    result.setdefault("template_params", _default_template_params(merchant, customer))
    return result


def _strip_word_ci(text: str, word: str) -> str:
    import re
    return re.sub(re.escape(word), "", text, flags=re.IGNORECASE).replace("  ", " ").strip()


def _sentence(text: str) -> str:
    """Ensure a clause ends with terminal punctuation before we concatenate
    something after it. Several dataset fields (category.digest[*].actionable
    in particular — true for every single item across all 5 categories, we
    checked) don't end in '.', which otherwise produces a run-on like
    '...in your SOPs Want a checklist?' when glued to the next sentence."""
    text = (text or "").rstrip()
    if text and not text.endswith((".", "!", "?", ":")):
        text += "."
    return text


def _sentence_lead_lower(text: str) -> str:
    """Lowercase only the leading character, for gluing a title onto a prior
    clause (e.g. '...trial found: {title}'). Deliberately does NOT lower()
    the whole string: a blanket .lower() mangles any acronym appearing
    anywhere in the title (RCT, DCI, GST, FSSAI, ...), which real research/
    compliance digest titles routinely contain -- and which a freshly
    judge-injected Phase-3 digest item is especially likely to contain,
    since we can't predict its exact wording in advance. Every other family
    that glues a digest title into prose (fam_regulation_change,
    fam_cde_opportunity) already keeps the title verbatim; this brings
    fam_research_digest in line with that instead of being the one place
    that silently lowercases embedded acronyms."""
    return (text[:1].lower() + text[1:]) if text else text


def _default_template_params(merchant: dict, customer: Optional[dict]) -> list[str]:
    if customer:
        return [customer_first_name(customer), merchant_display_name(merchant)]
    return [owner_salutation_safe(merchant)]


def owner_salutation_safe(merchant: dict) -> str:
    return g(merchant, "identity", "owner_first_name") or merchant_display_name(merchant)


# ---------------------------------------------------------------------------
# small language helper: pick a connector-phrase pack if code-mix applies
# ---------------------------------------------------------------------------

class Lang:
    """Very small Hinglish phrase pack. Used only when the merchant/customer's
    language preference AND the category's voice both support it — so we
    never impose code-mix on an english-only merchant, and never impose pure
    English on a merchant whose stated preference is hi-en mix
    (challenge-brief.md §5.7, and anti-pattern list in §11)."""

    def __init__(self, mix: bool, pure_hindi: bool = False):
        self.mix = mix
        self.pure_hindi = pure_hindi

    def want(self, hinglish: str, english: str) -> str:
        return hinglish if self.mix else english


def merchant_lang(category: dict, merchant: dict) -> Lang:
    return Lang(mix=uses_code_mix(category) and merchant_speaks_hindi(merchant))


def customer_lang(category: dict, customer: dict) -> Lang:
    return Lang(mix=customer_wants_code_mix(customer), pure_hindi=customer_pure_hindi(customer))


# ---------------------------------------------------------------------------
# FAMILY: digest-anchored (research / compliance / cde / trend)
# ---------------------------------------------------------------------------

def fam_research_digest(category, merchant, trigger, customer):
    item = freshest_digest_for_trigger(category, trigger, "research")
    name = owner_salutation(merchant, category)
    L = merchant_lang(category, merchant)

    if item:
        risk_signal = has_signal(merchant, "high_risk_adult_cohort")
        segment_note = ""
        if risk_signal and item.get("patient_segment") == "high_risk_adults":
            segment_note = L.want(" — aapke high-risk adult patients ke liye relevant",
                                    " — relevant to your high-risk adult patients")
        n = item.get("trial_n")
        n_clause = f"{n:,}-patient trial" if n else "recent study"
        body = (
            f"{name}, this week's {category.get('display_name', category.get('slug'))} digest "
            f"landed{segment_note}. {n_clause.capitalize()} found: {_sentence_lead_lower(item.get('title', ''))}. "
            f"Worth a 2-min look — {item.get('source', '')}. "
            f"{L.want('Draft ek patient-ed WhatsApp bana doon jo aap share kar sakein?', 'Should I put together a patient-ed WhatsApp you can send out?')}"
        )
        rationale = ("Specificity + trigger relevance from digest item "
                     f"'{item.get('id')}' (source-cited); merchant-fit via "
                     f"{'high_risk_adult_cohort signal' if risk_signal else 'category framing'}. "
                     "Curiosity + effort-externalization levers, single open CTA.")
        cta = "open_ended"
    else:
        # placeholder payload or missing digest id — degrade honestly, no invented citation
        body = (
            f"{name}, this week's {category.get('slug')} research/compliance digest is out. "
            f"{L.want('2-min padhne layak hai. Bhejun?', 'Worth a 2-min read — should I send it over?')}"
        )
        rationale = "Digest item id not resolvable in category context — degraded to a low-specificity, honest nudge rather than inventing a citation."
        cta = "open_ended"

    return {"body": body, "cta": cta, "rationale": rationale}


def fam_cde_opportunity(category, merchant, trigger, customer):
    item = freshest_digest_for_trigger(category, trigger, "cde", "training")
    name = owner_salutation(merchant, category)
    credits = g(trigger, "payload", "credits")
    fee = g(trigger, "payload", "fee", default="").replace("_", " ")
    if item:
        date_str = item.get("date", "")[:16].replace("T", ", ")
        body = (
            f"{name}, {item.get('title', 'a CDE session')} — {date_str}"
            + (f", {credits} credits" if credits else "")
            + (f", {fee}" if fee else "")
            + f". {item.get('summary', '')} Should I send the registration link?"
        )
        rationale = f"Anchored on digest item '{item.get('id')}' (date, credits, fee are all cited fields, nothing invented)."
    else:
        body = f"{name}, a CDE opportunity in your category just opened up — want details?"
        rationale = "Digest item unresolved — kept the claim generic rather than fabricating a date/credit count."
    return {"body": body, "cta": "open_ended", "rationale": rationale}


def fam_regulation_change(category, merchant, trigger, customer):
    item = freshest_digest_for_trigger(category, trigger, "compliance", "regulation")
    name = owner_salutation(merchant, category)
    deadline = g(trigger, "payload", "deadline_iso")
    if item:
        body = (
            f"{name}, compliance heads-up: {item.get('title', '')}. {item.get('summary', '')} "
            + (f"Deadline: {deadline}. " if deadline else "")
            + f"{_sentence(item.get('actionable', 'Worth reviewing your setup before it lands'))} "
            f"Should I put a checklist together for your practice?"
        )
        rationale = f"Regulation trigger anchored on digest '{item.get('id')}' + explicit deadline from payload; urgency={trigger.get('urgency')} reflected in directness. Loss-aversion lever (deadline)."
    else:
        body = f"{name}, heads-up — a regulation update affecting {category.get('slug')} is in motion. I'll send details the moment the source is confirmed — okay to hold till then?"
        rationale = "No resolvable digest item — avoided citing a fake deadline or circular number."
    return {"body": body, "cta": "binary", "rationale": rationale}


def fam_supply_alert(category, merchant, trigger, customer):
    name = owner_salutation(merchant, category)
    payload = g(trigger, "payload", default={}) or {}
    molecule = payload.get("molecule")
    batches = payload.get("affected_batches") or []
    mfr = payload.get("manufacturer")
    if molecule and not is_placeholder_payload(trigger):
        batch_str = ", ".join(batches) if batches else "specific batches"
        body = (
            f"{name}, voluntary recall alert: {molecule} ({batch_str}"
            + (f", {mfr}" if mfr else "") + f"). "
            f"Should I pull your repeat-Rx customers on this molecule so you can notify them?"
        )
        rationale = f"High-urgency (u={trigger.get('urgency')}) supply alert with molecule + batch numbers straight from payload; loss-aversion + effort-externalization (offer to pull the list) as in the seed conversation for this exact merchant."
        cta = "binary"
    else:
        body = f"{name}, a supply/recall alert just came in for your category — should I check if it touches your current stock?"
        rationale = "Placeholder payload — withheld molecule/batch specifics rather than inventing them; still surfaced the alert so nothing urgent is silently dropped."
        cta = "open_ended"
    return {"body": body, "cta": cta, "rationale": rationale}


def fam_category_seasonal(category, merchant, trigger, customer):
    name = owner_salutation(merchant, category)
    payload = g(trigger, "payload", default={}) or {}
    trends = payload.get("trends") or []
    if trends and not is_placeholder_payload(trigger):
        top = trends[:2]
        body = (
            f"{name}, seasonal shift for {category.get('slug')}: "
            + ", ".join(t.replace('_', ' ') for t in top) + ". "
            f"{'Shelf/stock action recommended. ' if payload.get('shelf_action_recommended') else ''}"
            f"Should I line up a reorder checklist for it?"
        )
        rationale = f"Cites {len(top)} real trend deltas from trigger payload; category_seasonal is external+data-driven, so specificity comes straight from payload, not category digest."
        cta = "binary"
    else:
        beat = seasonal_beat_for_month(category, month_abbr(trigger.get("expires_at")) or "")
        if beat:
            body = f"{name}, heads up: {beat.get('note')}. I can line up what usually helps this window — want that?"
            rationale = f"Payload was placeholder; fell back to category.seasonal_beats matching the trigger's expiry month — still a real, cited fact, just from a different context layer."
        else:
            body = f"{name}, a seasonal shift is coming up for {category.get('slug')} — should I check what it usually means for bookings?"
            rationale = "Payload and seasonal_beats both unresolvable — kept the message honest and low-specificity."
        cta = "open_ended"
    return {"body": body, "cta": cta, "rationale": rationale}


# alias category_trend_movement -> same handling as category_seasonal (both are
# external trend-shift triggers per challenge-brief.md §4.3)
def fam_category_trend_movement(category, merchant, trigger, customer):
    trend = g(category, "trend_signals", default=[])
    name = owner_salutation(merchant, category)
    if trend:
        t = trend[0]
        body = (
            f"{name}, '{t.get('query')}' searches are up {fmt_pct(t.get('delta_yoy'))} vs last year "
            f"in the {t.get('segment_age', 'relevant')} segment. Should I tweak your listing description to catch that?"
        )
        rationale = f"Anchored on category.trend_signals[0] ({t.get('query')}, real YoY delta) — curiosity + specificity."
    else:
        body = f"{name}, search interest is shifting in {category.get('slug')} this month — want me to dig into what's moving?"
        rationale = "No trend_signals available — generic, honest nudge."
    return {"body": body, "cta": "open_ended", "rationale": rationale}


# ---------------------------------------------------------------------------
# FAMILY: performance (spike / dip / seasonal dip)
# ---------------------------------------------------------------------------

def _perf_fact(merchant, trigger, want_negative: Optional[bool] = None):
    """Prefer trigger.payload (kind-specific, freshest); fall back to
    merchant.performance.delta_7d which is ALWAYS present, even on generated
    merchants — this is the single most useful fallback in the whole composer.

    `want_negative`: if set, the fallback is only used when its sign matches
    the trigger family (True for a dip, False for a spike) — otherwise a
    'dropped +2%' contradiction can happen when the fallback metric doesn't
    actually move in the direction the trigger kind implies."""
    payload = g(trigger, "payload", default={}) or {}
    if not is_placeholder_payload(trigger) and payload.get("metric"):
        return payload.get("metric"), payload.get("delta_pct"), payload.get("window", "7d"), payload.get("vs_baseline")
    # fallback to merchant.performance — try both metrics, keep the one
    # whose sign actually matches what this trigger family needs
    delta = g(merchant, "performance", "delta_7d", default={}) or {}
    candidates = [("calls", delta.get("calls_pct")), ("views", delta.get("views_pct"))]
    for metric, val in candidates:
        if val is None:
            continue
        if want_negative is True and val >= 0:
            continue
        if want_negative is False and val < 0:
            continue
        return metric, val, "7d", None
    return None, None, None, None


def fam_perf_dip(category, merchant, trigger, customer):
    name = owner_salutation(merchant, category)
    metric, delta, window, baseline = _perf_fact(merchant, trigger, want_negative=True)
    L = merchant_lang(category, merchant)
    if metric and delta is not None:
        base_clause = f" (vs {baseline}/day avg)" if baseline else ""
        follow_up = L.want(
            "Kuch specific wajah dikh rahi hai — check karke batati hoon?",
            "I've spotted a likely cause — want me to walk you through it?",
        )
        body = (
            f"{name}, your {metric} dropped {fmt_pct(delta)} over the last {window}{base_clause}. "
            f"{follow_up}"
        )
        rationale = f"Loss-aversion lever on a real {metric} delta ({fmt_pct(delta)}/{window}), sourced from " + ("trigger payload." if not is_placeholder_payload(trigger) else "merchant.performance.delta_7d fallback since trigger payload was a placeholder.")
        cta = "binary"
    else:
        body = f"{name}, I'm seeing softer numbers than usual this week — should I dig into what's behind it?"
        rationale = "No performance delta available anywhere in context — kept the claim vague rather than citing a fabricated percentage."
        cta = "open_ended"
    return {"body": body, "cta": cta, "rationale": rationale}


def fam_perf_spike(category, merchant, trigger, customer):
    name = owner_salutation(merchant, category)
    metric, delta, window, baseline = _perf_fact(merchant, trigger, want_negative=False)
    driver = g(trigger, "payload", "likely_driver")
    if metric and delta is not None and delta > 0:
        driver_clause = f" — looks like your {driver.replace('_', ' ')} is working" if driver else ""
        body = (
            f"{name}, your {metric} are up {fmt_pct(delta)} over the last {window}{driver_clause}. "
            f"Should we double down on whatever's driving it?"
        )
        rationale = f"Curiosity + social-validation on a real positive {metric} delta ({fmt_pct(delta)})" + (f", explicit driver ({driver}) cited from payload." if driver else ".")
        cta = "open_ended"
    else:
        body = f"{name}, some of your numbers ticked up this week — want me to find what's driving it so we can lean into it?"
        rationale = "Delta unresolvable — generic positive nudge, no invented number."
        cta = "open_ended"
    return {"body": body, "cta": cta, "rationale": rationale}


def fam_seasonal_perf_dip(category, merchant, trigger, customer):
    name = owner_salutation(merchant, category)
    payload = g(trigger, "payload", default={}) or {}
    note = payload.get("season_note", "").replace("_", " ")
    if payload.get("is_expected_seasonal") and note and not is_placeholder_payload(trigger):
        body = (
            f"{name}, the {fmt_pct(payload.get('delta_pct'))} dip in {payload.get('metric', 'views')} this week is "
            f"the usual {note} pattern — not a red flag. Okay if I hold retention-focused nudges instead of ad spend till it lifts?"
        )
        rationale = "Reassurance framing using is_expected_seasonal + season_note from payload — turns a dip into informed guidance instead of alarm, avoiding a false loss-aversion trigger."
        cta = "binary"
    else:
        beat = seasonal_beat_for_month(category, month_abbr(trigger.get("expires_at")) or "")
        if beat:
            body = f"{name}, numbers softening a bit right now is normal — {beat.get('note')}. Okay if I hold off on paid pushes till it turns?"
            rationale = "Payload placeholder; fell back to category.seasonal_beats for the reassurance context."
        else:
            body = f"{name}, noticing a seasonal-looking dip — should I confirm whether it's expected for your category right now?"
            rationale = "No seasonal grounding available anywhere — kept it a genuine open question rather than asserting seasonality."
        cta = "open_ended"
    return {"body": body, "cta": cta, "rationale": rationale}


# ---------------------------------------------------------------------------
# FAMILY: milestone
# ---------------------------------------------------------------------------

def fam_milestone_reached(category, merchant, trigger, customer):
    name = owner_salutation(merchant, category)
    payload = g(trigger, "payload", default={}) or {}
    metric, now, target = payload.get("metric"), payload.get("value_now"), payload.get("milestone_value")
    if metric and now is not None and target and not is_placeholder_payload(trigger):
        remaining = target - now
        imminent = payload.get("is_imminent")
        body = (
            f"{name}, you're at {now} {metric.replace('_', ' ')}"
            + (f" — {remaining} away from {target}!" if remaining > 0 else f" — just crossed {target}!")
            + f" {'Worth a post to mark it — should I draft one?' if imminent or remaining <= 0 else 'Worth calling out once you cross it.'}"
        )
        rationale = f"Milestone framing with exact counts from payload ({now}/{target}); social-proof/pride lever, low-friction CTA."
        cta = "open_ended" if (imminent or remaining <= 0) else "none"
    else:
        peer_reviews = g(category, "peer_stats", "avg_review_count")
        aggregate = g(merchant, "customer_aggregate", "total_unique_ytd")
        if peer_reviews and aggregate:
            body = f"{name}, your category's peer average is ~{peer_reviews} reviews — worth checking where you stand and whether a quick ask-for-review nudge makes sense?"
            rationale = "Milestone payload placeholder; substituted a real peer_stats benchmark comparison instead of a fabricated count."
            cta = "open_ended"
        else:
            body = f"{name}, you may be close to a milestone worth celebrating — want me to check your numbers?"
            rationale = "No milestone data anywhere in context — kept the claim speculative and offered to verify rather than asserting a number."
            cta = "open_ended"
    return {"body": body, "cta": cta, "rationale": rationale}


# ---------------------------------------------------------------------------
# FAMILY: subscription (renewal / winback / dormant / unverified)
# ---------------------------------------------------------------------------

def fam_renewal_due(category, merchant, trigger, customer):
    name = owner_salutation(merchant, category)
    sub = g(merchant, "subscription", default={}) or {}
    days = g(trigger, "payload", "days_remaining", default=sub.get("days_remaining"))
    amount = g(trigger, "payload", "renewal_amount")
    plan = sub.get("plan", g(trigger, "payload", "plan", default="your plan"))
    if days is not None:
        body = (
            f"{name}, your {plan} plan renews in {days} day{'s' if days != 1 else ''}"
            + (f" ({fmt_money(amount)})" if amount else "") + ". "
            f"Reply YES to renew now and skip any listing downtime, or STOP if you'd rather I check back later."
        )
        rationale = f"Renewal date/plan/amount sourced from merchant.subscription (always present) and/or trigger payload — no fabrication risk since subscription is a required field. Binary CTA per WA session-window constraint for action triggers."
        cta = "binary"
    else:
        body = f"{name}, wanted to flag your subscription status — want me to check the renewal timeline for you?"
        rationale = "days_remaining unresolvable in either context — degraded to an offer-to-check rather than a fabricated countdown."
        cta = "open_ended"
    return {"body": body, "cta": cta, "rationale": rationale}


def fam_winback_eligible(category, merchant, trigger, customer):
    name = owner_salutation(merchant, category)
    payload = g(trigger, "payload", default={}) or {}
    days_since = payload.get("days_since_expiry") or g(merchant, "subscription", "days_since_expiry")
    dip = payload.get("perf_dip_pct")
    lapsed_added = payload.get("lapsed_customers_added_since_expiry")
    if days_since:
        parts = [f"It's been {days_since} days since your listing went inactive."]
        if dip:
            parts.append(f"Views are down {fmt_pct(dip)} since then.")
        if lapsed_added:
            parts.append(f"~{lapsed_added} more customers have gone quiet in that window.")
        parts.append("Want to pick back up where we left off? No re-onboarding needed.")
        body = f"{name}, " + " ".join(parts)
        rationale = "Winback message anchored on real days-since-expiry (from subscription or payload) plus optional perf/lapse deltas; loss-aversion lever, low-friction re-entry CTA (no re-onboarding)."
        cta = "binary"
    else:
        body = f"{name}, noticed your listing's been quiet for a bit — want to pick back up?"
        rationale = "No expiry timeline resolvable — generic but honest winback nudge."
        cta = "binary"
    return {"body": body, "cta": cta, "rationale": rationale}


def fam_dormant_with_vera(category, merchant, trigger, customer):
    name = owner_salutation(merchant, category)
    payload = g(trigger, "payload", default={}) or {}
    days = payload.get("days_since_last_merchant_message")
    topic = payload.get("last_topic")
    if days is None:
        sig = has_signal(merchant, "dormant_with_vera")
        if sig:
            import re
            m = re.search(r"(\d+)d", sig)
            days = int(m.group(1)) if m else None
    if days:
        topic_clause = f" — we were last talking about {topic.replace('_', ' ')}" if topic else ""
        body = f"{name}, it's been {days} days since we last spoke{topic_clause}. Still want a hand with your listing, or should I check back later?"
        rationale = f"Dormancy day-count sourced from payload or merchant.signals fallback ('{sig if not days is payload.get('days_since_last_merchant_message') else 'payload'}'). Low-pressure re-opener, binary-ish exit-friendly CTA."
        cta = "binary"
    else:
        body = f"{name}, it's been a while — still want a hand with your listing?"
        rationale = "No dormancy day-count resolvable anywhere — kept generic."
        cta = "binary"
    return {"body": body, "cta": cta, "rationale": rationale}


def fam_gbp_unverified(category, merchant, trigger, customer):
    name = owner_salutation(merchant, category)
    payload = g(trigger, "payload", default={}) or {}
    uplift = payload.get("estimated_uplift_pct")
    path = (payload.get("verification_path") or "").replace("_", " ")
    uplift_clause = f" — verified listings typically see ~{fmt_pct(uplift)} more visibility" if uplift else ""
    body = (
        f"{name}, your Google listing isn't verified yet{uplift_clause}. "
        f"{('Verification is via ' + path + '. ') if path else ''}Should I start that for you? Takes under 5 minutes on your end."
    )
    rationale = "Uplift estimate and verification path both cited only when present in payload; effort-externalization ('5 minutes') lever."
    return {"body": body, "cta": "binary", "rationale": rationale}


# ---------------------------------------------------------------------------
# FAMILY: review theme
# ---------------------------------------------------------------------------

def fam_review_theme_emerged(category, merchant, trigger, customer):
    name = owner_salutation(merchant, category)
    payload = g(trigger, "payload", default={}) or {}
    theme, occ, trend, quote = (payload.get("theme"), payload.get("occurrences_30d"),
                                  payload.get("trend"), payload.get("common_quote"))
    if not (theme and occ) or is_placeholder_payload(trigger):
        rt = review_theme(merchant)
        if rt:
            theme, occ = rt.get("theme"), rt.get("occurrences_30d")
            quote = rt.get("common_quote")
            trend = None
    if theme and occ:
        quote_clause = f' — one review said "{quote}"' if quote else ""
        trend_clause = f" (trending {trend})" if trend else ""
        body = (
            f"{name}, {occ} reviews this month mention {theme.replace('_', ' ')}{trend_clause}{quote_clause}. "
            f"Should I draft a response template you can reuse?"
        )
        rationale = f"Review pattern with real occurrence count from " + ("trigger payload." if payload.get("theme") else "merchant.review_themes fallback.") + " Effort-externalization CTA."
        cta = "open_ended"
    else:
        body = f"{name}, a pattern is showing up in your recent reviews — should I pull the specifics for you?"
        rationale = "No review theme data resolvable in payload or merchant.review_themes — kept generic rather than inventing a theme/quote."
        cta = "open_ended"
    return {"body": body, "cta": cta, "rationale": rationale}


# ---------------------------------------------------------------------------
# FAMILY: competitor
# ---------------------------------------------------------------------------

def fam_competitor_opened(category, merchant, trigger, customer):
    name = owner_salutation(merchant, category)
    payload = g(trigger, "payload", default={}) or {}
    cname, dist, offer = payload.get("competitor_name"), payload.get("distance_km"), payload.get("their_offer")
    if cname and not is_placeholder_payload(trigger):
        offer_clause = f" running \"{offer}\"" if offer else ""
        body = (
            f"{name}, {cname} opened {dist}km away{offer_clause}. "
            f"Not saying panic — want me to check how your listing compares on the searches that matter?"
        )
        rationale = "Named competitor + distance + their real offer, all from payload (never fabricated). Curiosity lever, deliberately non-alarmist per anti-hype voice constraint."
        cta = "binary"
    else:
        body = f"{name}, there's new competition in your locality — should I check how your listing stacks up?"
        rationale = "Placeholder payload — withheld the competitor's name rather than inventing one (anti-fabrication constraint explicitly calls out fake competitor names)."
        cta = "open_ended"
    return {"body": body, "cta": cta, "rationale": rationale}


# ---------------------------------------------------------------------------
# FAMILY: festival / match-day (external calendar events)
# ---------------------------------------------------------------------------

def fam_festival_upcoming(category, merchant, trigger, customer):
    name = owner_salutation(merchant, category)
    payload = g(trigger, "payload", default={}) or {}
    fest, days_until = payload.get("festival"), payload.get("days_until")
    if fest and days_until is not None and not is_placeholder_payload(trigger):
        if days_until > 60:
            body = f"{name}, {fest} is {days_until} days out — early, but {category.get('slug')} bookings for it tend to fill fast. Should I draft a save-the-date post now, while you’ve still got the pick of slots?"
        else:
            body = f"{name}, {fest} is {days_until} days away — should I draft and queue a festival offer?"
        rationale = f"Festival + real day-count from payload; timing framing (early vs urgent) adapts to days_until rather than using one generic script."
        cta = "open_ended" if days_until > 30 else "binary"
    else:
        body = f"{name}, a seasonal/festival window is coming up for {category.get('slug')} — want me to check timing and draft something?"
        rationale = "Festival name/date unresolvable — kept generic."
        cta = "open_ended"
    return {"body": body, "cta": cta, "rationale": rationale}


def fam_ipl_match_today(category, merchant, trigger, customer):
    name = owner_salutation(merchant, category)
    payload = g(trigger, "payload", default={}) or {}
    match, venue = payload.get("match"), payload.get("venue")
    weeknight = payload.get("is_weeknight")
    if match and not is_placeholder_payload(trigger):
        # per category digest: weeknight matches outperform Saturdays for covers
        weeknight_note = "weeknight matches tend to outperform weekends for covers — worth pushing this one" if weeknight else "weekend matches skew home-watch, so keep it low-key rather than a big push"
        body = f"{name}, {match} tonight at {venue}. {weeknight_note.capitalize()}. Should I queue a match-night combo for tonight?"
        rationale = "Match + venue from payload; framing (push vs low-key) uses the category digest finding on weeknight-vs-Saturday performance — category + trigger fused correctly rather than a blanket IPL script."
        cta = "binary"
    else:
        body = f"{name}, there's a match tonight that could bring some extra footfall — should I queue a quick match-night special?"
        rationale = "Match detail unresolvable — generic but still timely nudge."
        cta = "binary"
    return {"body": body, "cta": cta, "rationale": rationale}


# ---------------------------------------------------------------------------
# FAMILY: active planning intent — CRITICAL anti-pattern guard
# (challenge-brief.md Pattern D: merchant already said yes, do NOT re-qualify)
# ---------------------------------------------------------------------------

def fam_active_planning_intent(category, merchant, trigger, customer):
    name = owner_salutation(merchant, category)
    payload = g(trigger, "payload", default={}) or {}
    topic = (payload.get("intent_topic") or "").replace("_", " ")
    last_msg = payload.get("merchant_last_message", "")
    # find something concrete from the category offer_catalog to make the
    # "draft" feel real rather than an empty promise
    catalog = g(category, "offer_catalog", default=[]) or []
    suggestion = catalog[0]["title"] if catalog else None
    if topic:
        concrete = f" I'd structure it around something like \"{suggestion}\" as the entry price point." if suggestion else ""
        body = (
            f"{name}, on the {topic} —{concrete} Drafting the full outline now; "
            f"I'll have it ready to review in a few minutes. Anything specific you want included?"
        )
        rationale = ("ACTION mode, not qualification mode — this directly targets the intent-handoff failure "
                     "(challenge-brief.md §9 Pattern D / §12.2): the merchant already committed "
                     f"(\"{last_msg[:60]}...\"), so the composer moves straight to 'drafting now' language "
                     "instead of re-asking whether they want to grow their business. Effort-externalization lever.")
        cta = "open_ended"
    else:
        body = f"{name}, picking up where we left off — I'm drafting the next step now. Anything you want me to prioritize?"
        rationale = "Planning-intent payload thin, but still defaulted to ACTION framing rather than re-qualifying, since the trigger kind itself signals the merchant already opted in."
        cta = "open_ended"
    return {"body": body, "cta": cta, "rationale": rationale}


# ---------------------------------------------------------------------------
# FAMILY: curious ask (compulsion lever #7 — the brief's biggest miss today)
# ---------------------------------------------------------------------------

def fam_curious_ask_due(category, merchant, trigger, customer):
    name = owner_salutation(merchant, category)
    templates = {
        "what_service_in_demand_this_week": "What's been your most-asked-for service this week?",
    }
    ask_key = g(trigger, "payload", "ask_template", default="")
    question = templates.get(ask_key, f"What's one thing about your {category.get('slug')} business you'd want more customers to know?")
    body = f"{name}, quick one — {question.lower() if not question[0].isupper() else question}"
    rationale = "Pure 'ask the merchant' lever (brief §10 lever #7 — called out as the biggest underused family in production Vera). No CTA needed beyond the question itself; genuinely low-friction and conversation-opening."
    return {"body": body, "cta": "open_ended", "rationale": rationale}


# ---------------------------------------------------------------------------
# CUSTOMER-SCOPE FAMILIES (send_as = merchant_on_behalf)
# ---------------------------------------------------------------------------

CATEGORY_EMOJI = {"dentists": "🦷", "salons": "💇", "gyms": "💪", "restaurants": "🍽️", "pharmacies": "💊"}
CATEGORY_PLACE_NOUN = {"dentists": "clinic", "salons": "salon", "gyms": "studio", "restaurants": "", "pharmacies": "pharmacy"}


def fam_recall_due(category, merchant, trigger, customer):
    cname = customer_first_name(customer) if customer else "there"
    mname = merchant_display_name(merchant)
    L = customer_lang(category, customer) if customer else Lang(False)
    payload = g(trigger, "payload", default={}) or {}
    service = (payload.get("service_due") or "").replace("_", " ")
    slots = payload.get("available_slots") or []
    offers = active_offers(merchant)
    price_offer = next((o for o in offers if "clean" in o.get("title", "").lower()), offers[0] if offers else None)

    slot_clause = ""
    if slots:
        labels = [s.get("label", "") for s in slots[:2]]
        slot_clause = L.want(f"Apke liye {len(labels)} slots ready hain: " + " ya ".join(f"**{l}**" for l in labels) + ". ",
                              f"{len(labels)} slots open: " + " or ".join(f"**{l}**" for l in labels) + ". ")
    # only add an offer/service clause if it's real, new information — a
    # generated (placeholder) trigger with no service_due and no active offer
    # has nothing further to say here, and appending a filler like "your
    # recall visit." just repeats the previous sentence
    offer_clause = ""
    if price_offer:
        offer_clause = f"{price_offer['title']}. "
    elif service:
        offer_clause = f"{service.capitalize()} — same as usual. "

    emoji = CATEGORY_EMOJI.get(category.get("slug"), "")
    place_noun = CATEGORY_PLACE_NOUN.get(category.get("slug"), "")
    # avoid "Dr. Meera's Dental Clinic's clinic here" — only append the noun
    # if the business name doesn't already contain it
    if place_noun and place_noun.lower() not in mname.lower():
        place_clause = f" {mname}'s {place_noun} here"
    else:
        place_clause = f" {mname} here"
    greeting = f"Hi {cname},{place_clause} {emoji} ".replace("  ", " ")

    body = (
        f"{greeting}"
        + L.want(f"Aapka {service or 'recall'} due hai. ", f"Your {service or 'recall'} is due. ")
        + slot_clause
        + offer_clause
        + L.want("Reply 1 ya 2, ya koi aur time batayein jo aapko suit kare.",
                 "Reply 1 or 2, or tell us a time that works for you.")
    )
    rationale = ("Customer-facing recall composed from real active offer ("
                 f"{'found: ' + price_offer['title'] if price_offer else 'none active — omitted price, used service name only, per anti-fabrication rule'}"
                 f") + real slots from trigger payload + language_pref-driven code-mix. Multi-choice CTA is the explicit "
                 "booking-flow exception noted in challenge-brief.md Appendix B.")
    return {"body": body, "cta": "binary", "rationale": rationale,
            "template_params": [cname, mname, service or "recall"]}


def fam_customer_lapsed(category, merchant, trigger, customer, hard: bool):
    cname = customer_first_name(customer) if customer else "there"
    mname = merchant_display_name(merchant)
    L = customer_lang(category, customer) if customer else Lang(False)
    payload = g(trigger, "payload", default={}) or {}
    offers = active_offers(merchant)
    offer = offers[0]["title"] if offers else None

    # Prefer the trigger's own real, freshest field when it's actually
    # present (e.g. trg_015_winback_rashmi ships payload.days_since_last_visit
    # directly) rather than deriving an approximation from last_visit vs.
    # trigger.expires_at -- expires_at is when the trigger LAPSES, not "now"
    # (compose() has no direct access to the tick's clock), so that derived
    # number was only ever a rough proxy and could drift from the real gap.
    day_source = None
    days = None
    real_days = payload.get("days_since_last_visit")
    if isinstance(real_days, (int, float)) and not is_placeholder_payload(trigger):
        days = int(real_days)
        day_source = "trigger.payload.days_since_last_visit (real, freshest)"
    else:
        last_visit = g(customer, "relationship", "last_visit") if customer else None
        if last_visit:
            approx = days_between(last_visit, trigger.get("expires_at"))
            if approx is not None:
                days = approx
                day_source = "approximated from customer.relationship.last_visit vs. trigger.expires_at (payload had no direct day count)"

    miss_clause = f" — it's been about {days} days since your last visit" if days else ""
    if hard:
        body = (
            f"Hi {cname}, {mname} here. Missed you{miss_clause}. "
            + (f"{offer} is on right now if you'd like to pick back up. " if offer else "Would love to have you back. ")
            + L.want("Ek slot book kar doon?", "Should I book you a slot?")
        )
    else:
        closing = L.want("Kuch help chahiye?", "Anything we can help with?")
        if offer:
            closing = L.want(f"{offer} chal raha hai abhi — interested?", f"{offer} is on right now — interested?")
        opener = L.want("Kaise ho.", "Hope all's well.")
        body = (
            f"Hi {cname}, {mname} here{miss_clause}. "
            + f"{opener} "
            + closing
        )
    rationale = (f"{'Hard' if hard else 'Soft'}-lapse winback; day count from {day_source or 'unresolvable — omitted rather than guessed'}, "
                 f"real active offer ({'yes: ' + offer if offer else 'none — fell back to a plain re-engagement ask'}), "
                 "customer language_pref honored for code-mix. Single binary-leaning CTA.")
    return {"body": body, "cta": "binary" if offer else "open_ended", "rationale": rationale,
            "template_params": [cname, mname]}


def fam_customer_lapsed_soft(category, merchant, trigger, customer):
    return fam_customer_lapsed(category, merchant, trigger, customer, hard=False)


def fam_customer_lapsed_hard(category, merchant, trigger, customer):
    return fam_customer_lapsed(category, merchant, trigger, customer, hard=True)


def fam_appointment_tomorrow(category, merchant, trigger, customer):
    cname = customer_first_name(customer) if customer else "there"
    mname = merchant_display_name(merchant)
    L = customer_lang(category, customer) if customer else Lang(False)
    payload = g(trigger, "payload", default={}) or {}
    time_label = payload.get("time_label") or payload.get("slot_label")
    if time_label and not is_placeholder_payload(trigger):
        body = f"Hi {cname}, quick reminder — {mname} tomorrow, {time_label}. " + L.want("Sab theek?", "All set on your end?")
        rationale = "Real slot time from payload cited directly."
        cta = "binary"
    else:
        # kind existing implies a real appointment; we just can't cite the specific time (placeholder payload)
        body = f"Hi {cname}, quick reminder about your appointment tomorrow with {mname}. " + L.want("Sab theek hai na?", "Still good on your end?")
        rationale = "Trigger kind confirms an appointment exists (that's the premise of this trigger firing), but payload was a placeholder so we withheld the specific time rather than inventing one."
        cta = "binary"
    return {"body": body, "cta": cta, "rationale": rationale, "template_params": [cname, mname]}


def fam_chronic_refill_due(category, merchant, trigger, customer):
    cname = customer_first_name(customer) if customer else "there"
    mname = merchant_display_name(merchant)
    L = customer_lang(category, customer) if customer else Lang(False)
    payload = g(trigger, "payload", default={}) or {}
    molecules = payload.get("molecule_list") or []
    runs_out = payload.get("stock_runs_out_iso")
    delivery_saved = payload.get("delivery_address_saved")
    if molecules and not is_placeholder_payload(trigger):
        mol_str = ", ".join(m.capitalize() for m in molecules[:3])
        runs_out_clause = f" Stock runs out around {runs_out[:10]}." if runs_out else ""
        delivery_clause = L.want(" Aapka saved address pe deliver kar doon?", " Deliver to your saved address as usual?") if delivery_saved else L.want(" Kahan deliver karun?", " Where should we deliver?")
        body = f"Hi {cname}, {mname} here — your {mol_str} refill is coming due.{runs_out_clause}{delivery_clause}"
        rationale = "Molecule list + stock-out date from payload; delivery-address branching from customer.preferences via payload flag. Binary/low-friction CTA appropriate for a repeat-purchase reminder."
        cta = "binary"
    else:
        body = f"Hi {cname}, {mname} here — thought you might be due for a refill on your regular medicines. Should we check what's running low?"
        rationale = "Molecule list unresolvable (placeholder payload) — avoided naming a specific drug the customer wasn't confirmed to be on."
        cta = "open_ended"
    return {"body": body, "cta": cta, "rationale": rationale, "template_params": [cname, mname]}


def fam_trial_followup(category, merchant, trigger, customer):
    cname = customer_first_name(customer) if customer else "there"
    mname = merchant_display_name(merchant)
    payload = g(trigger, "payload", default={}) or {}
    options = payload.get("next_session_options") or []
    if options and not is_placeholder_payload(trigger):
        label = options[0].get("label", "")
        body = f"Hi {cname}, hope the trial at {mname} went well! Next session's open for {label} if you'd like to continue — want me to hold that slot?"
        rationale = "Real next-session slot label from payload."
        cta = "binary"
    else:
        body = f"Hi {cname}, hope the trial at {mname} went well! Want to see what's next available?"
        rationale = "No slot option resolvable — kept the CTA open rather than naming a fake slot."
        cta = "open_ended"
    return {"body": body, "cta": cta, "rationale": rationale, "template_params": [cname, mname]}


def fam_wedding_package_followup(category, merchant, trigger, customer):
    cname = customer_first_name(customer) if customer else "there"
    mname = merchant_display_name(merchant)
    payload = g(trigger, "payload", default={}) or {}
    days_to = payload.get("days_to_wedding")
    next_step = (payload.get("next_step_window_open") or "").replace("_", " ")
    if days_to and next_step and not is_placeholder_payload(trigger):
        body = (
            f"Hi {cname}, {days_to} days to the big day! Your trial's locked in — the "
            f"{next_step} window is open now, and it's the kind of thing that's easy to leave too late. "
            f"Should I pencil in a start date?"
        )
        rationale = "Real days_to_wedding + next_step_window_open cited from payload; mild loss-aversion ('easy to leave too late') without overclaiming outcomes — stays within salon voice taboos (no 'guaranteed glow')."
        cta = "open_ended"
    else:
        body = f"Hi {cname}, excited for your big day! Should we plan out your pre-wedding schedule with {mname}?"
        rationale = "Wedding-specific timeline unresolvable — generic but warm follow-up."
        cta = "open_ended"
    return {"body": body, "cta": cta, "rationale": rationale, "template_params": [cname, mname]}


# ---------------------------------------------------------------------------
# generic fallback — any kind not explicitly handled, or total data drought
# ---------------------------------------------------------------------------

def _fallback_anchor(category: dict, trigger: dict) -> tuple[str, str]:
    """Return a human-readable, verifiable anchor for a novel trigger.

    This deliberately reads only explicit, display-safe fields.  It gives
    post-submission trigger kinds a grounded route without leaking enum names
    or turning arbitrary payload keys into merchant-facing jargon.
    """
    item = freshest_digest_for_trigger(category, trigger)
    if item and item.get("title"):
        source = f" Source: {item['source']}." if item.get("source") else ""
        return _sentence(str(item["title"])) + source, "new category digest item"

    payload = g(trigger, "payload", default={}) or {}
    for key in ("headline", "title", "event_name", "topic", "service_due"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return _sentence(value.replace("_", " ")), f"trigger payload.{key}"

    metric, delta = payload.get("metric"), payload.get("delta_pct")
    if isinstance(metric, str) and isinstance(delta, (int, float)):
        return (f"{metric.replace('_', ' ')} changed {fmt_pct(delta)} over {payload.get('window', 'the latest window')}."), "trigger metric"
    return "", ""

def _generic_fallback(category, merchant, trigger, customer):
    """Used only for a trigger `kind` this composer has never seen. We
    deliberately do NOT expose the raw internal kind string to the merchant
    (e.g. 'active_planning_intent', 'customer_lapsed_hard') — that's exactly
    the internal-jargon leak the judge penalizes. The kind name is still
    logged in `rationale`, which is judge-facing metadata, never in `body`,
    which is merchant-facing."""
    if customer:
        cname = customer_first_name(customer)
        mname = merchant_display_name(merchant)
        anchor, source = _fallback_anchor(category, trigger)
        if anchor:
            body = f"Hi {cname}, a quick update from {mname}: {anchor} Would you like us to help with the next step?"
        else:
            body = f"Hi {cname}, quick note from {mname} — wanted to check in with you. Anything I can help with?"
        rationale = (f"Unrecognized customer-scope trigger kind '{trigger.get('kind')}' — no matching family "
                     "handler. Deliberately did NOT surface the raw kind string in the merchant-facing body "
                     f"(that would be an internal-jargon leak); used {source or 'a safe generic check-in'} instead.")
    else:
        name = owner_salutation(merchant, category)
        anchor, source = _fallback_anchor(category, trigger)
        offer = active_offers(merchant)
        offer_clause = f" I can shape the next step around your active {offer[0]['title']}." if offer else ""
        if anchor:
            body = f"{name}, a fresh update worth acting on: {anchor}{offer_clause} Should I turn this into a simple draft for you?"
        else:
            # ground in whatever real signal exists so this isn't purely generic,
            # but phrase it in plain language rather than the raw signal string
            sig = (g(merchant, "signals", default=[]) or [None])[0]
            sig_clause = " — something worth looking at on your listing" if sig else ""
            body = f"{name}, quick check-in{sig_clause}. Got a minute to talk through it?"
        rationale = (f"Unrecognized merchant-scope trigger kind '{trigger.get('kind')}' — no matching family "
                     f"handler. Grounded in {source or 'the presence/absence of a real merchant signal'}, but phrased "
                     "in plain language rather than exposing the raw signal string or kind name to the merchant.")
    return {"body": body, "cta": "open_ended", "rationale": rationale}


# ---------------------------------------------------------------------------
# dispatch table
# ---------------------------------------------------------------------------

FAMILY_DISPATCH = {
    # merchant-scope external
    "research_digest": fam_research_digest,
    "cde_opportunity": fam_cde_opportunity,
    "regulation_change": fam_regulation_change,
    "supply_alert": fam_supply_alert,
    "category_seasonal": fam_category_seasonal,
    "category_trend_movement": fam_category_trend_movement,
    "festival_upcoming": fam_festival_upcoming,
    "ipl_match_today": fam_ipl_match_today,
    "competitor_opened": fam_competitor_opened,
    "weather_heatwave": fam_festival_upcoming,   # same "external calendar event" framing
    "local_news_event": fam_festival_upcoming,

    # merchant-scope internal
    "perf_dip": fam_perf_dip,
    "perf_spike": fam_perf_spike,
    "seasonal_perf_dip": fam_seasonal_perf_dip,
    "milestone_reached": fam_milestone_reached,
    "renewal_due": fam_renewal_due,
    "winback_eligible": fam_winback_eligible,
    "dormant_with_vera": fam_dormant_with_vera,
    "gbp_unverified": fam_gbp_unverified,
    "review_theme_emerged": fam_review_theme_emerged,
    "active_planning_intent": fam_active_planning_intent,
    "curious_ask_due": fam_curious_ask_due,
    "scheduled_recurring": fam_curious_ask_due,

    # customer-scope internal
    "recall_due": fam_recall_due,
    "customer_lapsed_soft": fam_customer_lapsed_soft,
    "customer_lapsed_hard": fam_customer_lapsed_hard,
    "appointment_tomorrow": fam_appointment_tomorrow,
    "chronic_refill_due": fam_chronic_refill_due,
    "trial_followup": fam_trial_followup,
    "wedding_package_followup": fam_wedding_package_followup,
    "unplanned_slot_open": fam_trial_followup,  # both are "here's an open slot" framing
}

# --- End composer.py ---

# --- Begin conversation_handlers.py ---
"""
conversation_handlers.py — respond(state, merchant_message) -> dict

Handles the three replay scenarios called out explicitly in
challenge-testing-brief.md §4 Phase 4:
  1. Auto-reply hell     — same canned WA-Business auto-reply repeated 3-4x
  2. Intent transition   — merchant commits ("ok let's do it") after
                            qualification; must switch to ACTION, not re-ask
  3. Hostile / off-topic — abuse, then an unrelated ask; stay on-mission,
                            polite, don't over-apologize into a loop

Also implements the two other open challenges from challenge-brief.md §12:
  4. graceful stop after repeated unanswered nudges / explicit "not interested"
  5. per-turn language detection (rough) so a Hindi reply gets a Hindi-leaning
     response even if the merchant's profile default is English

ConversationState is a plain dict so bot.py can serialize it trivially;
this module only reads/mutates that dict, it never touches the context store.
"""

import re
from typing import Any, Optional

# ---------------------------------------------------------------------------
# constants / heuristics
# ---------------------------------------------------------------------------

# Canned WhatsApp Business auto-reply phrasing (English + common Hindi/Hinglish
# variants seen in challenge-brief.md §9 Pattern B and general WA Business
# defaults). Not exhaustive by design — combined with the repeat-detector
# below, which is the more reliable signal per the brief's own hint:
# "same message verbatim 3+ times = auto-reply".
AUTO_REPLY_PHRASES = [
    "thank you for contacting", "thanks for contacting", "we will get back to you",
    "will respond shortly", "automated assistant", "currently unavailable",
    "aapki jaankari ke liye", "team tak pahunchane", "hamari team tak",
    "automated reply", "this is an automated", "we'll reply soon",
    "out of office", "busy right now",
]

HOSTILE_PHRASES = [
    "stop messaging", "spam", "fuck", "useless", "shut up", "scam",
    "harass", "block you", "reported", "bakwas", "bewakoof",
]

NOT_INTERESTED_PHRASES = [
    "not interested", "no thanks", "nahi chahiye", "don't message",
    "leave me alone", "unsubscribe", "remove me",
]

COMMIT_PHRASES = [
    "ok lets do it", "ok let's do it", "let's do it", "lets do it", "go ahead",
    "yes lets", "yes let's", "sounds good", "sure go ahead", "proceed",
    "confirm", "yes please do", "haan kar do", "theek hai kar do", "kar do",
    "chalo karte hain",
]

QUALIFYING_STARTERS = [
    "would you", "do you want", "are you interested", "can you tell",
    "what if", "how about", "would it help", "kya aap", "chahiye kya",
]

OFF_TOPIC_HINTS = [
    "gst", "income tax", "loan", "visa", "legal advice", "personal problem",
]

HINDI_HINT_CHARS = re.compile(r"[\u0900-\u097F]")  # Devanagari block
HINGLISH_WORDS = {"hai", "kya", "nahi", "aap", "kar", "karo", "chahiye", "theek", "haan", "bhai", "yaar"}


def _normalize(text: str) -> str:
    return re.sub(r"\s+", " ", text.strip().lower())


def _looks_hindi_ish(text: str) -> bool:
    low = text.lower()
    if HINDI_HINT_CHARS.search(text):
        return True
    words = set(re.findall(r"[a-z]+", low))
    return len(words & HINGLISH_WORDS) >= 1


def _contains_any(text: str, phrases: list[str]) -> bool:
    low = text.lower()
    return any(p in low for p in phrases)


def is_auto_reply_message(text: str) -> bool:
    """Public, deterministic auto-reply classifier used across conversations.

    The official replay may issue each repeated WA-Business reply under a new
    conversation id, so per-conversation state alone is not enough.
    """
    return _contains_any(_normalize(text), AUTO_REPLY_PHRASES)


# ---------------------------------------------------------------------------
# state helpers — state is a plain dict, created/owned by bot.py per conversation_id
# ---------------------------------------------------------------------------

def new_state(merchant_id: Optional[str] = None, customer_id: Optional[str] = None,
              merchant_name: str = "there", first_body: str = "") -> dict:
    return {
        "merchant_id": merchant_id,
        "customer_id": customer_id,
        "merchant_name": merchant_name,
        "sent_bodies": [first_body] if first_body else [],
        "incoming_history": [],     # list of normalized incoming messages
        "consecutive_auto_replies": 0,
        "consecutive_unanswered": 0,   # bumped by bot.py when a `wait` times out without a reply
        "turns": 0,
        "ended": False,
        "mode": "pitch",            # "pitch" | "action" | "ended"
    }


# ---------------------------------------------------------------------------
# core entry point
# ---------------------------------------------------------------------------

def respond(state: dict, merchant_message: str) -> dict:
    """Given conversation-so-far `state` (mutated in place) and the latest
    incoming message, decide: send / wait / end."""
    state["turns"] = state.get("turns", 0) + 1
    norm = _normalize(merchant_message)
    state.setdefault("incoming_history", []).append(norm)

    if state.get("ended"):
        return {"action": "end", "rationale": "Conversation already ended; ignoring further input."}

    # --- 1. auto-reply detection (verbatim repeat OR canned-phrase match) ---
    is_repeat = state["incoming_history"].count(norm) >= 2  # this message seen before
    is_canned_phrase = _contains_any(norm, AUTO_REPLY_PHRASES)

    if is_repeat or is_canned_phrase:
        state["consecutive_auto_replies"] = state.get("consecutive_auto_replies", 0) + 1
    else:
        state["consecutive_auto_replies"] = 0

    if state["consecutive_auto_replies"] >= 2:
        # per challenge-brief.md Pattern B: try ONE redirect after first
        # detection, then exit gracefully rather than burning more turns.
        state["ended"] = True
        state["mode"] = "ended"
        return {
            "action": "end",
            "rationale": (f"Detected {state['consecutive_auto_replies']} consecutive auto-reply-shaped "
                          "messages (repeat-verbatim or canned WA-Business phrasing) after already "
                          "attempting one human redirect. Exiting to avoid burning further turns, "
                          "per the auto-reply anti-pattern in challenge-brief.md §3."),
        }
    if state["consecutive_auto_replies"] == 1:
        body = _auto_reply_redirect(state)
        _record_sent(state, body)
        return {"action": "send", "body": body, "cta": "binary",
                "rationale": "First auto-reply-shaped message detected — trying one direct, low-effort redirect to reach a human before giving up (mirrors challenge-brief.md Pattern B)."}

    # --- 2. hostile detection ---
    if _contains_any(norm, HOSTILE_PHRASES):
        state["ended"] = True
        state["mode"] = "ended"
        body = _hostile_graceful_exit(state)
        # brief's own scoring example accepts either a graceful "end" or an
        # apologetic "send" that stops the ask — we choose "end" with a warm
        # sign-off so the bot doesn't keep the thread open after abuse, while
        # still being able to re-engage later via a fresh trigger.
        return {"action": "end",
                "rationale": "Hostile/abusive message detected. Exiting the conversation politely rather than re-pitching or arguing; a future trigger can re-open contact later. No apology-loop, no defensiveness."}

    # --- 3. not-interested / opt-out ---
    if _contains_any(norm, NOT_INTERESTED_PHRASES):
        state["ended"] = True
        state["mode"] = "ended"
        return {"action": "end",
                "rationale": "Explicit not-interested/opt-out signal — graceful exit per challenge-brief.md §12.5 ('knowing when to stop')."}

    # --- 4. too many unanswered nudges already (set externally by bot.py on timeouts) ---
    if state.get("consecutive_unanswered", 0) >= 3:
        state["ended"] = True
        state["mode"] = "ended"
        return {"action": "end",
                "rationale": "3 consecutive nudges went unanswered — stopping rather than continuing to push, per challenge-brief.md §12.5."}

    # --- 5. off-topic but not hostile: acknowledge briefly, redirect to mission ---
    if _contains_any(norm, OFF_TOPIC_HINTS) and not _contains_any(norm, COMMIT_PHRASES):
        body = _off_topic_redirect(state)
        _record_sent(state, body)
        return {"action": "send", "body": body, "cta": "open_ended",
                "rationale": "Off-mission question detected. One-line honest boundary + redirect back to the original thread, staying polite and on-mission without ignoring the merchant."}

    # --- 6. intent / commitment transition: switch pitch -> action immediately ---
    if _contains_any(norm, COMMIT_PHRASES) or state.get("mode") == "action":
        state["mode"] = "action"
        body = _action_mode_response(state, merchant_message)
        _record_sent(state, body)
        return {"action": "send", "body": body, "cta": "open_ended",
                "rationale": ("Merchant signaled explicit commitment — switching straight to ACTION "
                              "language ('done'/'sending'/'here's the draft'), never re-asking a "
                              "qualifying question. This is the exact failure mode challenge-brief.md "
                              "Pattern D calls out.")}

    # --- 7. default: acknowledge + advance the pitch by one concrete step ---
    body = _pitch_mode_response(state, merchant_message)
    _record_sent(state, body)
    return {"action": "send", "body": body, "cta": "open_ended",
            "rationale": "Neutral/engaged reply — advancing the conversation with one concrete next step, still in pitch mode since no explicit commitment or objection was detected."}


def _record_sent(state: dict, body: str) -> None:
    state.setdefault("sent_bodies", []).append(body)


# ---------------------------------------------------------------------------
# response builders
# ---------------------------------------------------------------------------

def _lang_pack(state: dict, merchant_message: str):
    """Very rough per-turn language detection (challenge-brief.md §12.4):
    if this specific incoming message looks Hindi/Hinglish, mirror that in
    the reply even if the stored default is English."""
    return _looks_hindi_ish(merchant_message)


def _auto_reply_redirect(state: dict) -> str:
    name = state.get("merchant_name", "there")
    return (f"Samajh gayi — but this one's quick and needs your OK directly, "
            f"not the front-desk. 2 minutes, want to just glance at it yourself?")


def _hostile_graceful_exit(state: dict) -> str:
    name = state.get("merchant_name", "there")
    return f"Understood — I'll stop here. All the best with the business, and I'm around if that changes."


def _off_topic_redirect(state: dict) -> str:
    return ("That's outside what I can help with directly, sorry — I'm just here for your listing/growth side. "
            "Back to what we were on: want me to go ahead with the draft?")


def _action_mode_response(state: dict, merchant_message: str) -> str:
    hindi = _lang_pack(state, merchant_message)
    if hindi:
        return "Done — abhi shuru kar rahi hoon. Kuch minute mein draft ready hoga, main yahin bhej dungi review ke liye."
    return "Done — starting now. I'll have a draft ready in a few minutes and send it here for you to review."


def _pitch_mode_response(state: dict, merchant_message: str) -> str:
    hindi = _lang_pack(state, merchant_message)
    if hindi:
        return "Theek hai! Bataiye, kya aap isse aage badhana chahenge — main abhi shuru kar sakti hoon."
    return "Good to know — want me to go ahead and set that up, or is there something you'd want to see first?"

# --- End conversation_handlers.py ---

# --- Begin bot.py ---
#!/usr/bin/env python3
"""
bot.py — magicpin AI Challenge submission ("Vera 2.0")

Implements the 5 endpoints defined in challenge-testing-brief.md §2:
    POST /v1/context    receive a context push (idempotent by version)
    POST /v1/tick       periodic wake-up; bot may initiate up to 20 actions
    POST /v1/reply      receive a merchant/customer reply; bot must respond
    GET  /v1/healthz    liveness probe
    GET  /v1/metadata   bot identity

Architecture (see README.md for the full writeup):
    contexts.py               safe accessors over raw context dicts
    composer.py                deterministic compose(category, merchant,
                                trigger, customer?) — the message engine
    conversation_handlers.py  respond(state, merchant_message) — multi-turn
    bot.py (this file)        HTTP surface + in-memory state store

State is entirely in-memory (per the testing brief: "Storing in memory is
fine; just don't restart between calls"). Run with:
    uvicorn bot:app --host 0.0.0.0 --port 8080
"""


import time
import uuid
from datetime import datetime, timezone
from typing import Any, Optional

from fastapi import FastAPI, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field


START_TIME = time.time()
TICK_ACTION_CAP = 20  # challenge-testing-brief.md §5

app = FastAPI(title="Vera 2.0 — magicpin AI Challenge bot")

# ---------------------------------------------------------------------------
# in-memory stores
# ---------------------------------------------------------------------------

# (scope, context_id) -> {"version": int, "payload": dict}
CONTEXTS: dict[tuple[str, str], dict[str, Any]] = {}

# conversation_id -> conversation_handlers state dict
CONVERSATIONS: dict[str, dict[str, Any]] = {}

# suppression_key -> last-sent unix ts, for basic trigger-level dedup
# (challenge-brief.md §4.3: suppression_key exists "for dedup")
SUPPRESSION_LOG: dict[str, float] = {}
SUPPRESSION_TTL_SECONDS = 24 * 3600  # don't re-fire the same suppression_key within 24h

# trigger_id -> set of (merchant_id, customer_id) already actioned, so a tick
# never re-proposes a brand new conversation for a trigger already handled
TRIGGERED_ALREADY: set[tuple[str, str]] = set()

# merchant/message -> count.  The official auto-reply replay deliberately
# changes conversation_id between repeated WA-Business replies.
AUTO_REPLY_FINGERPRINTS: dict[tuple[str, str], int] = {}

CONSENT_BY_TRIGGER_KIND = {
    "recall_due": "recall_reminders",
    "appointment_tomorrow": "appointment_reminders",
    "chronic_refill_due": ("refill_reminders", "delivery_notifications"),
    "customer_lapsed_soft": ("winback_offers", "promotional_offers"),
    "customer_lapsed_hard": ("winback_offers", "promotional_offers"),
    "trial_followup": ("kids_program_updates", "program_updates", "treatment_followup"),
    "wedding_package_followup": ("bridal_package_followup", "promotional_offers"),
}


def _get_ctx(scope: str, context_id: str) -> Optional[dict]:
    entry = CONTEXTS.get((scope, context_id))
    return entry["payload"] if entry else None


def _category_for_merchant(merchant: dict) -> Optional[dict]:
    slug = merchant.get("category_slug")
    return _get_ctx("category", slug) if slug else None


def _counts_by_scope() -> dict[str, int]:
    counts = {"category": 0, "merchant": 0, "customer": 0, "trigger": 0}
    for (scope, _cid) in CONTEXTS.keys():
        counts[scope] = counts.get(scope, 0) + 1
    return counts


# ---------------------------------------------------------------------------
# GET /v1/healthz
# ---------------------------------------------------------------------------

@app.get("/v1/healthz")
async def healthz():
    return {
        "status": "ok",
        "uptime_seconds": int(time.time() - START_TIME),
        "contexts_loaded": _counts_by_scope(),
    }


# ---------------------------------------------------------------------------
# GET /v1/metadata
# ---------------------------------------------------------------------------

@app.get("/v1/metadata")
async def metadata():
    return {
        "team_name": "Vera 2.0",
        "team_members": ["Claude (Anthropic)"],
        "model": "deterministic-template-composer-v1 (no LLM in the hot path)",
        "approach": (
            "compose() dispatches by trigger.kind into ~25 family templates, each "
            "grounded directly in the 4 context dicts with a graceful degrade path "
            "when payloads are placeholders/sparse (generated, non-seed merchants "
            "and ~40% of generated triggers). No LLM call in /v1/tick or /v1/reply "
            "hot paths -> deterministic, fast, zero hallucination risk by "
            "construction. See README.md for full rationale."
        ),
        "contact_email": "team@example.com",
        "version": "1.0.0",
        "submitted_at": datetime.now(timezone.utc).isoformat(),
    }


# ---------------------------------------------------------------------------
# POST /v1/context
# ---------------------------------------------------------------------------

class CtxBody(BaseModel):
    scope: str
    context_id: str
    version: int
    payload: dict[str, Any]
    delivered_at: str


VALID_SCOPES = {"category", "merchant", "customer", "trigger"}


@app.post("/v1/context")
async def push_context(body: CtxBody):
    if body.scope not in VALID_SCOPES:
        return JSONResponse(status_code=400, content={
            "accepted": False,
            "reason": "invalid_scope",
            "details": f"scope must be one of {sorted(VALID_SCOPES)}",
        })

    key = (body.scope, body.context_id)
    cur = CONTEXTS.get(key)

    if cur and cur["version"] == body.version:
        # idempotent no-op re-post of the same version
        return {"accepted": True, "ack_id": f"ack_{body.context_id}_v{body.version}",
                "stored_at": datetime.now(timezone.utc).isoformat()}

    if cur and cur["version"] > body.version:
        return JSONResponse(status_code=409, content={
            "accepted": False, "reason": "stale_version", "current_version": cur["version"],
        })

    CONTEXTS[key] = {"version": body.version, "payload": body.payload}
    return {"accepted": True, "ack_id": f"ack_{body.context_id}_v{body.version}",
            "stored_at": datetime.now(timezone.utc).isoformat()}


# ---------------------------------------------------------------------------
# POST /v1/tick
# ---------------------------------------------------------------------------

class TickBody(BaseModel):
    now: str
    available_triggers: list[str] = Field(default_factory=list)


def _suppressed(suppression_key: str, now_ts: float) -> bool:
    last = SUPPRESSION_LOG.get(suppression_key)
    return bool(last) and (now_ts - last) < SUPPRESSION_TTL_SECONDS


def _tick_time(value: str) -> datetime:
    """Parse the caller's clock once so expiry and suppression are reproducible."""
    parsed = parse_iso_date(value)
    if parsed is None:
        raise HTTPException(status_code=422, detail="now must be a valid ISO-8601 timestamp")
    return parsed


@app.post("/v1/tick")
async def tick(body: TickBody):
    now = _tick_time(body.now)
    now_ts = now.timestamp()
    actions: list[dict] = []

    for trigger_id in body.available_triggers:
        if len(actions) >= TICK_ACTION_CAP:
            break

        trigger = _get_ctx("trigger", trigger_id)
        if not trigger:
            continue  # we were never pushed this trigger's payload; skip silently

        expires_at = parse_iso_date(trigger.get("expires_at"))
        if expires_at is not None and expires_at <= now:
            continue  # the action is no longer timely; never send stale outreach

        merchant_id = trigger.get("merchant_id")
        customer_id = trigger.get("customer_id")
        merchant = _get_ctx("merchant", merchant_id) if merchant_id else None
        if not merchant:
            continue  # can't compose without the merchant we'd be writing about

        category = _category_for_merchant(merchant)
        if not category:
            continue  # no category context yet — restraint over a voiceless guess

        customer = _get_ctx("customer", customer_id) if customer_id else None
        if trigger.get("scope") == "customer" and not customer:
            continue  # customer-scope trigger with no customer context pushed yet
        if trigger.get("scope") == "customer":
            consent_scope = CONSENT_BY_TRIGGER_KIND.get(trigger.get("kind"))
            if not customer_has_consent(customer, consent_scope):
                continue  # customer exists, but has not opted into this outreach purpose

        suppression_key = trigger.get("suppression_key") or f"{trigger_id}:{merchant_id}"
        if _suppressed(suppression_key, now_ts):
            continue  # already sent this exact thing recently — restraint is rewarded

        dedup_key = (merchant_id, customer_id or "")
        conv_key = f"{trigger_id}:{dedup_key[0]}:{dedup_key[1]}"
        if conv_key in TRIGGERED_ALREADY:
            continue

        composed = compose(category, merchant, trigger, customer)

        conversation_id = f"conv_{merchant_id}_{trigger_id}_{uuid.uuid4().hex[:6]}"
        display_name = merchant_display_name(merchant)

        state = new_state(merchant_id=merchant_id, customer_id=customer_id,
                           merchant_name=display_name, first_body=composed["body"])
        CONVERSATIONS[conversation_id] = state

        SUPPRESSION_LOG[suppression_key] = now_ts
        TRIGGERED_ALREADY.add(conv_key)

        actions.append({
            "conversation_id": conversation_id,
            "merchant_id": merchant_id,
            "customer_id": customer_id,
            "send_as": composed["send_as"],
            "trigger_id": trigger_id,
            "template_name": f"vera_{trigger.get('kind', 'generic')}_v1",
            "template_params": composed.get("template_params", []),
            "body": composed["body"],
            "cta": composed["cta"],
            "suppression_key": suppression_key,
            "rationale": composed["rationale"],
        })

    return {"actions": actions}


# ---------------------------------------------------------------------------
# POST /v1/reply
# ---------------------------------------------------------------------------

class ReplyBody(BaseModel):
    conversation_id: str
    merchant_id: Optional[str] = None
    customer_id: Optional[str] = None
    from_role: str
    message: str
    received_at: str
    turn_number: int


@app.post("/v1/reply")
async def reply(body: ReplyBody):
    state = CONVERSATIONS.get(body.conversation_id)
    if state is None:
        # judge replayed a conversation we don't have local state for (e.g.
        # a fresh replay-test scenario) — bootstrap minimal state so we can
        # still respond sensibly rather than erroring out.
        merchant = _get_ctx("merchant", body.merchant_id) if body.merchant_id else None
        display_name = merchant_display_name(merchant) if merchant else "there"
        state = new_state(merchant_id=body.merchant_id, customer_id=body.customer_id,
                           merchant_name=display_name)
        CONVERSATIONS[body.conversation_id] = state

    if is_auto_reply_message(body.message):
        fingerprint = (body.merchant_id or "", _normalize(body.message))
        AUTO_REPLY_FINGERPRINTS[fingerprint] = AUTO_REPLY_FINGERPRINTS.get(fingerprint, 0) + 1
        if AUTO_REPLY_FINGERPRINTS[fingerprint] >= 2:
            state["ended"] = True
            state["mode"] = "ended"
            return {
                "action": "end",
                "rationale": "Repeated WA-Business auto-reply detected across conversation ids; ending instead of spending another turn on an automated responder.",
            }

    result = conv_respond(state, body.message)

    # anti-repetition guard (challenge-testing-brief.md §10 penalty: -2 per
    # verbatim repeat). If the handler produced something we've already sent
    # in this conversation, fall back to a short, honest, non-repetitive nudge.
    if result.get("action") == "send":
        sent_before = state.get("sent_bodies", [])[:-1]  # exclude the one just recorded
        if result["body"] in sent_before:
            result["body"] = "Just circling back on this — still worth a look when you get a sec?"
            result["rationale"] += " [anti-repetition guard: original response matched a prior send verbatim, substituted a short honest circle-back instead]"

    return result


# ---------------------------------------------------------------------------
# optional: teardown (challenge-testing-brief.md §11 — wipe state at test end)
# ---------------------------------------------------------------------------

@app.post("/v1/teardown")
async def teardown():
    CONTEXTS.clear()
    CONVERSATIONS.clear()
    SUPPRESSION_LOG.clear()
    TRIGGERED_ALREADY.clear()
    AUTO_REPLY_FINGERPRINTS.clear()
    return {"status": "wiped"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8080)

# --- End bot.py ---
